Terminal
knewplay/book-programming-essential pull request #2
Opened 2023-07-18 14:23 UTC by andreigue

- Under Appendix > tools.md, completed main section titles
- Completed Terminal > Importance
- Completed Terminal > Fundamentals subsections

2023-07-19 18:09 UTC, hpyhacking requested changes

2023-07-19 18:09 UTC, hpyhacking commented on Appendix/tools.md
Can this file be submitted separately in other PR? 
If this is an outline, please specify.

2023-07-19 19:12 UTC, andreigue commented on Appendix/tools.md
I will do that

2023-07-24 14:30 UTC, hpyhacking approved these changes

2023-07-24 16:32 UTC, merged