Chapter4 loops
knewplay/book-programming-essential pull request #31
Opened 2023-10-23 18:05 UTC by andreigue

- Write chapter 4
- Edit the question section to the new format
- Yet to add images

2023-10-23 18:45 UTC, hpyhacking requested changes
Separate changing for Chapter 1-3 in other PR.

2023-10-23 19:14 UTC, jp524 approved these changes

2023-10-23 19:14 UTC, jp524 commented on index.md
> +### [Chapter 3: Logic and Decision Making](./programming-fundamentals/chapter3.md)
Remove file extension `.md` here and for chapter 4.

2023-10-23 19:14 UTC, jp524 commented on programming-fundamentals/chapter4.md
> +Recall the humanoid robot from [Chapter 2 Activity #2](./chapter2.md#activity-2). With your understanding of loops from this chapter, describe the commands you would provide to ensure the robot walks
Remove the file extension `.md`.

2023-10-26 19:11 UTC, jp524 approved these changes

2023-10-26 21:12 UTC, hpyhacking approved these changes

2023-10-30 14:55 UTC, merged